import { Order, AuditEvent } from '../types'
import { products, merchants } from './mockProducts'

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'user-1',
    items: [
      {
        productId: 'prod-1',
        product: products[0],
        quantity: 1,
        price: 139999,
      },
      {
        productId: 'prod-2',
        product: products[1],
        quantity: 1,
        price: 24999,
      },
    ],
    total: 164998,
    subtotal: 164998,
    discount: 0,
    tax: 0,
    status: 'delivered',
    paymentStatus: 'successful',
    createdAt: new Date('2026-08-20'),
    estimatedDelivery: new Date('2026-08-25'),
    merchant: merchants[0],
  },
  {
    id: 'ORD-002',
    customerId: 'user-1',
    items: [
      {
        productId: 'prod-3',
        product: products[2],
        quantity: 2,
        price: 8999,
      },
    ],
    total: 17998,
    subtotal: 17998,
    discount: 0,
    tax: 0,
    status: 'shipped',
    paymentStatus: 'successful',
    createdAt: new Date('2026-08-25'),
    estimatedDelivery: new Date('2026-08-28'),
    merchant: merchants[1],
  },
  {
    id: 'ORD-003',
    customerId: 'user-1',
    items: [
      {
        productId: 'prod-6',
        product: products[5],
        quantity: 1,
        price: 45999,
      },
    ],
    total: 45999,
    subtotal: 45999,
    discount: 0,
    tax: 0,
    status: 'confirmed',
    paymentStatus: 'successful',
    createdAt: new Date('2026-08-28'),
    estimatedDelivery: new Date('2026-09-02'),
    merchant: merchants[0],
  },
]

export const mockAuditTrail: AuditEvent[] = [
  {
    id: 'evt-1',
    timestamp: new Date('2026-08-28T10:00:00'),
    type: 'request',
    description: 'Customer requested: "Find me a laptop under ₹60,000"',
    actor: 'customer-1',
    metadata: { query: 'laptop under 60000', platform: 'AI Chat' },
    status: 'success',
  },
  {
    id: 'evt-2',
    timestamp: new Date('2026-08-28T10:01:00'),
    type: 'search',
    description: 'AI searched products matching criteria',
    actor: 'ai-agent',
    metadata: { results: 5, category: 'Laptops', maxPrice: 60000 },
    status: 'success',
  },
  {
    id: 'evt-3',
    timestamp: new Date('2026-08-28T10:02:00'),
    type: 'recommendation',
    description: 'AI recommended: Dell XPS 15 as best value option',
    actor: 'ai-agent',
    metadata: { productId: 'prod-4', reason: 'Best performance-to-price ratio' },
    status: 'success',
  },
  {
    id: 'evt-4',
    timestamp: new Date('2026-08-28T10:03:00'),
    type: 'recommendation',
    description: 'AI suggested MacBook Pro 14" as premium alternative',
    actor: 'ai-agent',
    metadata: { productId: 'prod-1', type: 'upsell', value: '+₹20,000' },
    status: 'success',
  },
  {
    id: 'evt-5',
    timestamp: new Date('2026-08-28T10:05:00'),
    type: 'approval',
    description: 'Customer approved MacBook Pro 14" recommendation',
    actor: 'customer-1',
    metadata: { productId: 'prod-1' },
    status: 'success',
  },
  {
    id: 'evt-6',
    timestamp: new Date('2026-08-28T10:06:00'),
    type: 'order',
    description: 'Order created: MacBook Pro 14" + Sony Headphones',
    actor: 'ai-agent',
    metadata: { orderId: 'ORD-001', items: 2, total: 164998 },
    status: 'success',
  },
  {
    id: 'evt-7',
    timestamp: new Date('2026-08-28T10:07:00'),
    type: 'payment',
    description: 'Payment initiated via Razorpay',
    actor: 'payment-gateway',
    metadata: { orderId: 'ORD-001', amount: 164998 },
    status: 'pending',
  },
  {
    id: 'evt-8',
    timestamp: new Date('2026-08-28T10:08:00'),
    type: 'payment',
    description: 'Payment successful: Transaction ID RZP-1234567890',
    actor: 'payment-gateway',
    metadata: { orderId: 'ORD-001', transactionId: 'RZP-1234567890' },
    status: 'success',
  },
  {
    id: 'evt-9',
    timestamp: new Date('2026-08-28T10:09:00'),
    type: 'order',
    description: 'Order confirmed and sent to merchant',
    actor: 'system',
    metadata: { orderId: 'ORD-001', merchant: 'TechHub Electronics' },
    status: 'success',
  },
  {
    id: 'evt-10',
    timestamp: new Date('2026-08-28T11:00:00'),
    type: 'support',
    description: 'Customer contacted support about delivery timeline',
    actor: 'customer-1',
    metadata: { orderId: 'ORD-001', type: 'chat' },
    status: 'success',
  },
  // Failed payment example
  {
    id: 'evt-11',
    timestamp: new Date('2026-08-26T14:30:00'),
    type: 'payment',
    description: 'Payment failed: Insufficient funds',
    actor: 'payment-gateway',
    metadata: { orderId: 'ORD-FAILED-001', amount: 45999, errorCode: 'INSUFFICIENT_FUNDS' },
    status: 'failed',
  },
  {
    id: 'evt-12',
    timestamp: new Date('2026-08-26T14:31:00'),
    type: 'payment',
    description: 'Customer notified of payment failure and retry option',
    actor: 'system',
    metadata: { orderId: 'ORD-FAILED-001' },
    status: 'success',
  },
]

export const mockMerchantStats = {
  totalRevenue: 3245672,
  aiGeneratedRevenue: 1876543,
  totalOrders: 12834,
  conversionRate: 4.2,
  averageOrderValue: 8945,
  upsellRevenue: 623851,
  failedPayments: 234,
  supportHandoffs: 156,
  topProducts: [products[0], products[1], products[2], products[3], products[4]],
}
