import { Product, Merchant } from '../types'

export const merchants: Merchant[] = [
  {
    id: 'merchant-1',
    name: 'TechHub Electronics',
    logo: 'https://ui-avatars.com/api/?name=Tech+Hub&background=3B82F6&color=fff&size=128&bold=true',
    rating: 4.8,
    verified: true,
  },
  {
    id: 'merchant-2',
    name: 'Fashion Forward',
    logo: 'https://ui-avatars.com/api/?name=Fashion+Forward&background=EC4899&color=fff&size=128&bold=true',
    rating: 4.6,
    verified: true,
  },
  {
    id: 'merchant-3',
    name: 'Premium Goods Co',
    logo: 'https://ui-avatars.com/api/?name=Premium+Goods&background=8B5CF6&color=fff&size=128&bold=true',
    rating: 4.7,
    verified: true,
  },
  {
    id: 'merchant-4',
    name: 'Budget Deals Store',
    logo: 'https://ui-avatars.com/api/?name=Budget+Deals&background=F97316&color=fff&size=128&bold=true',
    rating: 4.4,
    verified: true,
  },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'MacBook Pro 14" M2',
    price: 139999,
    originalPrice: 149999,
    rating: 4.9,
    reviewCount: 324,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80&auto=format&fit=crop',
    description: 'Powerful laptop for professionals and developers',
    availability: 'In Stock',
    category: 'Laptops',
    features: [
      '14-inch Liquid Retina XDR display',
      "Apple M2 chip with 10-core CPU",
      '16GB unified memory',
      '512GB SSD storage',
      'Up to 17 hours battery life',
    ],
    merchant: merchants[0],
    sku: 'MB-PRO-14-M2-001',
  },
  {
    id: 'prod-2',
    name: 'Sony WH-1000XM5 Headphones',
    price: 24999,
    originalPrice: 29999,
    rating: 4.7,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80&auto=format&fit=crop',
    description: 'Industry-leading noise cancellation headphones',
    availability: 'In Stock',
    category: 'Audio',
    features: [
      'Industry-leading noise cancellation',
      '30-hour battery life',
      'Hi-Res Audio with LDAC',
      'Multipoint connection',
      'Premium sound quality',
    ],
    merchant: merchants[0],
    sku: 'SONY-WH-1000XM5',
  },
  {
    id: 'prod-3',
    name: 'Nike Air Max 90',
    price: 8999,
    originalPrice: 9999,
    rating: 4.6,
    reviewCount: 287,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80&auto=format&fit=crop',
    description: 'Classic and comfortable everyday sneaker',
    availability: 'In Stock',
    category: 'Footwear',
    features: [
      'Air Max unit for comfort',
      'Durable rubber outsole',
      'Padded collar and tongue',
      'Lightweight design',
      'Available in multiple colors',
    ],
    merchant: merchants[1],
    sku: 'NIKE-AIR-MAX-90',
  },
  {
    id: 'prod-4',
    name: 'Dell XPS 15 Laptop',
    price: 119999,
    originalPrice: 134999,
    rating: 4.8,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80&auto=format&fit=crop',
    description: 'Premium Windows laptop with stunning display',
    availability: 'In Stock',
    category: 'Laptops',
    features: [
      '15.6-inch OLED display',
      'Intel Core i7 processor',
      '16GB RAM',
      '512GB SSD',
      'NVIDIA RTX 3050 graphics',
    ],
    merchant: merchants[0],
    sku: 'DELL-XPS-15-2024',
  },
  {
    id: 'prod-5',
    name: 'Levi\'s Original Jeans',
    price: 3499,
    originalPrice: 4499,
    rating: 4.5,
    reviewCount: 456,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80&auto=format&fit=crop',
    description: 'Timeless denim jeans perfect for any occasion',
    availability: 'In Stock',
    category: 'Clothing',
    features: [
      '100% cotton denim',
      'Traditional fit',
      'Classic blue wash',
      'Riveted pockets',
      'Comfortable and durable',
    ],
    merchant: merchants[1],
    sku: 'LEVIS-501-BLUE',
  },
  {
    id: 'prod-6',
    name: 'Samsung 4K Smart TV 55"',
    price: 45999,
    originalPrice: 54999,
    rating: 4.7,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80&auto=format&fit=crop',
    description: 'Crystal clear 4K television with smart features',
    availability: 'In Stock',
    category: 'Electronics',
    features: [
      '55-inch 4K UHD display',
      '120Hz refresh rate',
      'HDR10+ support',
      'Smart TV apps',
      'Voice control',
    ],
    merchant: merchants[0],
    sku: 'SAMSUNG-55Q70-4K',
  },
  {
    id: 'prod-7',
    name: 'Canon EOS R7 Camera',
    price: 129999,
    originalPrice: 145999,
    rating: 4.9,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80&auto=format&fit=crop',
    description: 'Professional mirrorless camera for creators',
    availability: 'Limited',
    category: 'Photography',
    features: [
      '32.5MP full-frame sensor',
      '6K video recording',
      'In-body stabilization',
      'Dual SD UHS-II cards',
      'Professional autofocus',
    ],
    merchant: merchants[2],
    sku: 'CANON-EOS-R7',
  },
  {
    id: 'prod-8',
    name: 'Apple Watch Series 8',
    price: 39999,
    originalPrice: 45999,
    rating: 4.8,
    reviewCount: 623,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&auto=format&fit=crop',
    description: 'Advanced health and fitness tracking smartwatch',
    availability: 'In Stock',
    category: 'Wearables',
    features: [
      'Always-on Retina display',
      'Temperature sensing',
      'Blood oxygen monitoring',
      'ECG app',
      'Water resistant',
    ],
    merchant: merchants[0],
    sku: 'APPLE-WATCH-S8-45',
  },
  {
    id: 'prod-9',
    name: 'Budget Android Phone',
    price: 12999,
    originalPrice: 15999,
    rating: 4.3,
    reviewCount: 891,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80&auto=format&fit=crop',
    description: 'Affordable smartphone with solid performance',
    availability: 'In Stock',
    category: 'Mobile',
    features: [
      '6.5-inch HD display',
      'MediaTek processor',
      '4GB RAM',
      '128GB storage',
      '50MP rear camera',
    ],
    merchant: merchants[3],
    sku: 'ANDROID-BUDGET-2024',
  },
  {
    id: 'prod-10',
    name: 'Premium Leather Backpack',
    price: 5999,
    originalPrice: 7999,
    rating: 4.6,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80&auto=format&fit=crop',
    description: 'Stylish and durable leather backpack for travel',
    availability: 'In Stock',
    category: 'Bags',
    features: [
      'Genuine leather',
      'Multiple compartments',
      'Laptop pocket',
      'Water-resistant',
      'Lifetime warranty',
    ],
    merchant: merchants[2],
    sku: 'LEATHER-BACKPACK-001',
  },
]

export const getProductById = (id: string): Product | undefined => {
  return products.find((p) => p.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((p) => p.category === category)
}

export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery) ||
      p.category.toLowerCase().includes(lowerQuery)
  )
}
